### PR TITLE
refactor: update dependencies and example app

### PR DESCRIPTION
**Pull request by kriss-u**
Previously, RNSVG was incorrectly used as dependency instead of devDependency.
Furthermore, the version was "^12.1.0". RNSVG has introduced fabric support
from version 13.x.x.
Since this package doesn't have to rely on specific version of RNSVG, it's better
to have this change.

The old example is removed and new example with RN 0.69.5 is added.
Yarn is used as package manager. This is a common convention for React apps.

The react native JS source files aren't changed except for some type introduction.

### CODE REVIEW

**Comment by kriss-u** [comment]
Fixes #15

**Comment by weahforsage** [comment]
Thanks for the PR.

**Comment by weahforsage** [comment]
PLUS, Since I don't have enough time to maintenance this repo, As always PR welcome.

**Comment by weahforsage** [comment]
I'm aware of that. Will update ASAP.

**Comment by weahforsage** [comment]
Its's live on npm, for some reason yarn package publishing is delaying.

**Comment by Jemaz** [comment]
@weahforsage Thanks! And thanks for all your hard work! 🙏

**Pull request merged**
